//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为,并且如果
//     重新生成代码,这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------


//INSTANT C# NOTE: Formerly VB project-level imports:
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Drawing;
using System.Diagnostics;
using System.Windows.Forms;
using System.Linq;
using System.Xml.Linq;
using System.Threading.Tasks;
using System;

namespace QQ_Login
{
	namespace Properties
	{

		//此类是由 StronglyTypedResourceBuilder
		//类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
		//若要添加或移除成员,请编辑 .ResX 文件,然后重新运行 ResGen
		//(以 /str 作为命令选项),或重新生成 VS 项目。
		///<summary>
		///  一个强类型的资源类,用于查找本地化的字符串等。
		///</summary>
		[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"), System.Diagnostics.DebuggerNonUserCodeAttribute(), System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
		internal static class Resources
		{

			private static System.Resources.ResourceManager resourceMan;

			private static System.Globalization.CultureInfo resourceCulture;

			///<summary>
			///  返回此类使用的缓存的 ResourceManager 实例。
			///</summary>
			[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static System.Resources.ResourceManager ResourceManager
			{
				get
				{
					if (object.ReferenceEquals(resourceMan, null))
					{
						System.Resources.ResourceManager temp = new System.Resources.ResourceManager("QQ_Login.Properties.Resources", typeof(Resources).Assembly);
						resourceMan = temp;
					}
					return resourceMan;
				}
			}

			///<summary>
			///  重写当前线程的 CurrentUICulture 属性
			///  重写当前线程的 CurrentUICulture 属性。
			///</summary>
			[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
			internal static System.Globalization.CultureInfo Culture
			{
				get
				{
					return resourceCulture;
				}
				set
				{
					resourceCulture = value;
				}
			}

			///<summary>
			///  查找 System.Byte[] 类型的本地化资源。
			///</summary>
			internal static byte[] libeay32
			{
				get
				{
					object obj = ResourceManager.GetObject("libeay32", resourceCulture);
					return (byte[])obj;
				}
			}
		}
	}

}